import puppeteer from 'puppeteer-core';
const targets = process.argv.slice(2).map(Number);
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new' });
const page = await browser.newPage(); await page.setViewport({ width: 1000, height: 700 });
await page.goto('http://localhost:4321/play/', { waitUntil: 'domcontentloaded', timeout: 60000 }); await new Promise(r => setTimeout(r, 3500)); await page.mouse.click(500, 400);
const porthole = await page.evaluate(() => new Promise(res => { const img = new Image(); img.onload = () => { const c = document.createElement('canvas'); c.width = img.width; c.height = img.height; const x = c.getContext('2d'); x.drawImage(img, 0, 0); const d = x.getImageData(0, 0, c.width, c.height).data; const frames = []; for (let f = 0; f * 470 < img.height; f++) { let minx = 1e9, miny = 1e9, maxx = -1, maxy = -1, n = 0; for (let y = f * 470; y < Math.min(img.height, f * 470 + 464); y++) for (let xx = 0; xx < img.width; xx++) { const i = (y * img.width + xx) * 4; const r = d[i], g = d[i+1], b = d[i+2], a = d[i+3]; if (a > 200 && r < 150 && g > 150 && b > 170) { n++; if (xx < minx) minx = xx; if (xx > maxx) maxx = xx; if (y < miny) miny = y; if (y > maxy) maxy = y; } } frames.push({ frame: f, glassPixels: n, bbox: n ? [minx, miny - f * 470, maxx, maxy - f * 470] : null, center: n ? [Math.round((minx + maxx) / 2), Math.round((miny + maxy) / 2) - f * 470] : null }); } res({ w: img.width, h: img.height, frames }); }; img.onerror = () => res('img error'); img.src = '/play/image/layers/rocket-sprite.png'; }));
console.log('porthole:', JSON.stringify(porthole));
const dump = () => { const st = document.getElementById('container').getBoundingClientRect(); const q = id => { const e = document.getElementById(id); if (!e) return null; const r = e.getBoundingClientRect(); const cs = getComputedStyle(e); return { x: Math.round(r.left - st.left), y: Math.round(r.top - st.top), w: Math.round(r.width), h: Math.round(r.height), z: cs.zIndex, disp: cs.display, vis: cs.visibility, op: cs.opacity, tf: cs.transform, clip: cs.clipPath, bgpos: cs.backgroundPosition, pad: cs.padding, left: cs.left, top: cs.top, bottom: cs.bottom }; };
  return { scrollY, movement: scrollState.layersMovement, ale: q('ale-container'), aleInner: q('ale'), rocket: q('rocket'), links: q('links-container'), contact: q('contact-container'), titleContact: q('title-contact'), stage: [Math.round(st.width), Math.round(st.height)], aleParent: document.getElementById('ale-container').parentElement.id, rocketParent: document.getElementById('rocket').parentElement.id, rocketNext: (document.getElementById('rocket').nextElementSibling||{}).id, aleNext: (document.getElementById('ale-container').nextElementSibling||{}).id }; };
await page.keyboard.down('ArrowRight');
for (const t of targets) { for (let g = 0; g < 6000; g++) { if ((await page.evaluate(() => scrollY)) >= t) break; await new Promise(r => setTimeout(r, 30)); } await page.keyboard.up('ArrowRight'); await new Promise(r => setTimeout(r, 1200)); console.log(t, JSON.stringify(await page.evaluate(dump))); await page.screenshot({ path: `${process.argv[1].replace('probe-end.mjs','')}pe${t}.png` }); await page.keyboard.down('ArrowRight'); }
await page.keyboard.up('ArrowRight'); await browser.close();
